-- #0429 TEST
CREATE TABLE TEST
(
  ID       NULL    ,
  NAME     NULL    ,
  AGE      NULL    ,
  ADDRESS  NULL    ,
  SALARY   NULL    
);

CREATE TABLE DEPARTMENT
(
  DEPT TEXT NOT NULL,
  NAME          TEXT NOT NULL,
  PRIMARY KEY (DEPARTMENT_ID)
);

INSERT INTO TEST (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (1, 'Paul', 32, 'California', 20000.00 );
INSERT INTO TEST (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (2, 'Allen', 25, 'Texas', 15000.00 );
INSERT INTO TEST (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (3, 'Teddy', 23, 'Norway', 20000.00 );
INSERT INTO TEST (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (4, 'Mark', 25, 'Rich-Mond ', 65000.00 );
INSERT INTO TEST (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (5, 'David', 27, 'Texas', 85000.00 );
INSERT INTO TEST (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (6, 'Kim', 22, 'South-Hall', 45000.00 );

INSERT INTO DEPARTMENT VALUES('ITB','IT Billing');
INSERT INTO DEPARTMENT VALUES('ENG','ENGINEERING');

SELECT * FROM TEST;
SELECT * FROM TEST where age is not null;
SELECT * FROM TEST where name like 'ki%';
SELECT * FROM TEST where name like 'p__l';
SELECT * FROM TEST where name like '%a%';
SELECT * FROM TEST where name like '_a%';
SELECT * FROM TEST where age in (25,27);
SELECT * FROM TEST where age not in (25,27);
SELECT * FROM TEST where age between 25 and 27;
SELECT * FROM TEST where age in (27) and salary>=65000;
SELECT * FROM TEST where age >=25 or salary>=65000;

SELECT * FROM TEST ORDER BY name ASC;
SELECT * FROM TEST ORDER BY name,age ASC;
SELECT * FROM TEST ORDER BY age DESC;

INSERT INTO TEST VALUES (7, 'Dylan', 26, 'France', 7800.00);
INSERT INTO TEST VALUES (8, 'Luke', 27, 'Newyork', 65000.00);
INSERT INTO TEST VALUES (9, 'Justin', 32, 'NewMexico', 50800.00);

SELECT NAME, SUM(SALARY) AS TOTAL FROM TEST GROUP BY NAME;
SELECT NAME, SUM(SALARY) FROM TEST GROUP BY NAME ORDER BY NAME;
SELECT COUNT(*),COUNT(AGE)FROM TEST WHERE AGE>24 ;

SELECT NAME, AGE, 'YES' AS yesorno FROM TEST;
SELECT C.ID,C.NAME,C.AGE,D.DEPT FROM TEST AS C, DEPARTMENT AS D WHERE C.ID=D.EMP_ID;
SELECT C.ID AS TEST_ID, C.NAME AS COMPANY_NAME, C.AGE, D.DEPT FROM COMPANY AS C,DEPARTMENT AS D WHERE C.ID=D.EMP_ID;