--#0507 TEST

CREATE TABLE TEST(
ID INT PRIMARY KEY NOT NULL,
NAME TEXT NOT NULL,
AGE INT NOT NULL,
ADDRESS CHAR(50),
SALARY REAL

);

CREATE TABLE TEST_BKP(
ID INT PRIMARY KEY NOT NULL,
NAME TEXT NOT NULL,
AGE INT NOT NULL,
ADDRESS CHAR(50),
SALARY REAL

);

CREATE TABLE DEPARTMENT(
ID INT PRIMARY KEY NOT NULL,
DEPT CHAR(50) NOT NULL,
EMP_ID INT NOT NULL );

CREATE TABLE OLD_COMPANY(
ID INT PRIMARY KEY NOT NULL,
NAME TEXT NOT NULL,
AGE INT NOT NULL,
ADDRESS CHAR(50),
SALARY REAL

);

INSERT INTO TEST (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (1, 'Paul', 32, 'California', 20000.00 );
INSERT INTO TEST (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (2, 'Allen', 25, 'Texas', 15000.00 );
INSERT INTO TEST (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (3, 'Teddy', 23, 'Norway', 20000.00 );
INSERT INTO TEST (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (4, 'Mark', 25, 'Rich-Mond ', 65000.00 );
INSERT INTO TEST (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (5, 'David', 27, 'Texas', 85000.00 );
INSERT INTO TEST (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (6, 'Kim', 22, 'South-Hall', 45000.00 );
INSERT INTO TEST (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (10, 'Smith', 25, 'Texas', 35000.00 );

INSERT INTO TEST_BKP (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (1, 'Paul', 32, 'California', 20000.00 );
INSERT INTO TEST_BKP (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (2, 'Allen', 25, 'Texas', 15000.00 );
INSERT INTO TEST_BKP (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (3, 'Teddy', 23, 'Norway', 20000.00 );
INSERT INTO TEST_BKP (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (4, 'Mark', 25, 'Rich-Mond ', 65000.00 );
INSERT INTO TEST_BKP (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (5, 'David', 27, 'Texas', 85000.00 );
INSERT INTO TEST_BKP (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (6, 'Kim', 22, 'South-Hall', 45000.00 );
INSERT INTO TEST_BKP (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (10, 'Smith', 25, 'Texas', 35000.00 );

INSERT INTO DEPARTMENT (ID, DEPT, EMP_ID) VALUES (1, 'IT Billing', 1 );
INSERT INTO DEPARTMENT (ID, DEPT, EMP_ID) VALUES (2, 'Engineering', 2 );
INSERT INTO DEPARTMENT (ID, DEPT, EMP_ID) VALUES (3, 'Finance', 7 );
INSERT INTO DEPARTMENT (ID, DEPT, EMP_ID) VALUES (4, 'IT Billing', 1 );
INSERT INTO DEPARTMENT (ID, DEPT, EMP_ID) VALUES (5, 'Finance', 7 );


INSERT INTO OLD_COMPANY (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (1, 'Paul', 32, 'California', 20000.00 );
INSERT INTO OLD_COMPANY (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (5, 'David', 27, 'Texas', 85000.00 );
INSERT INTO OLD_COMPANY (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (6, 'Kim', 22, 'South-Hall', 45000.00 );
INSERT INTO OLD_COMPANY (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (10, 'Smith', 25, 'Texas', 35000.00 );
INSERT INTO OLD_COMPANY (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (19, 'James', 28, 'Austin', 85000.00 );


SELECT TEST.*,DEPARTMENT.*
FROM TEST CROSS JOIN DEPARTMENT;

SELECT EMP_ID,TEST.NAME,DEPT,OLD_COMPANY.NAME
FROM TEST INNER JOIN DEPARTMENT ON TEST.ID=DEPARTMENT.EMP_ID
INNER JOIN OLD_COMPANY
ON TEST.ID=OLD_COMPANY.ID;

SELECT EMP_ID,NAME,DEPT
FROM TEST INNER JOIN DEPARTMENT ON TEST.ID=DEPARTMENT.EMP_ID;

SELECT ID,NAME,AGE,ADDRESS,SALARY
FROM TEST INNER JOIN OLD_COMPANY ON TEST.ID=OLD_COMPANY.ID;

SELECT TEST.ID,TEST.NAME,DEPARTMENT.DEPT FROM TEST LEFT OUTER JOIN DEPARTMENT ON TEST.ID=DEPARTMENT.EMP_ID;
SELECT TEST.ID,TEST.NAME,OLD_COMPANY.NAME FROM TEST LEFT OUTER JOIN OLD_COMPANY ON TEST.ID=OLD_COMPANY.ID;
SELECT TEST.NAME,AGE,DEPT,EMP_ID FROM (SELECT*FROM TEST WHERE SALARY>2000)AS TEST 
LEFT OUTER JOIN DEPARTMENT ON TEST.ID=DEPARTMENT.EMP_ID;

SELECT EMP_ID,NAME,DEPT FROM TEST INNER JOIN DEPARTMENT ON TEST.ID=DEPARTMENT.EMP_ID
UNION SELECT EMP_ID,NAME,DEPT FROM TEST LEFT OUTER JOIN DEPARTMENT ON TEST.ID=DEPARTMENT.EMP_ID;

SELECT EMP_ID,NAME,DEPT FROM TEST INNER JOIN DEPARTMENT ON TEST.ID=DEPARTMENT.EMP_ID
UNION ALL SELECT EMP_ID,NAME,DEPT FROM TEST LEFT OUTER JOIN DEPARTMENT ON TEST.ID=DEPARTMENT.EMP_ID;

SELECT NAME, ADDRESS,
CASE NAME 
When 'Paul' THEN SALARY
WHEN 'David' then AGE
ELSE 'ETC'
END AS NAME_CASE
FROM TEST;

SELECT ID,max(NAME) AS NAME, ADDRESS,
CASE 
When NAME =='Paul' THEN SALARY
END AS NAME01_CASE,
CASE
WHEN NAME=='David' THEN AGE
END AS NAME02_CASE
FROM TEST GROUP BY ADDRESS;

SELECT*FROM OLD_COMPANY
WHERE ID IN (SELECT ID FROM TEST
WHERE SALARY>45000);

SELECT AGE FROM TEST
WHERE EXISTS (SELECT AGE FROM TEST AS SUB_TEST
WHERE TEST.ID=SUB_TEST.ID AND SALARY>65000);

INSERT INTO TEST_BKP
SELECT*FROM TEST
WHERE ID IN (SELECT ID FROM TEST);

UPDATE TEST SET SALARY=SALARY*1.5
WHERE AGE IN (SELECT AGE FROM TEST_BKP WHERE AGE>=27);

DELETE FROM TEST
WHERE AGE IN (SELECT AGE FROM TEST_BKP WHERE AGE>=27);

SELECT * FROM TEST_BKP;
SELECT * FROM OLD_COMPANY;
SELECT * FROM TEST;
SELECT * FROM DEPARTMENT;

select date('now', 'start of month','+1 month','-1 day');
select datetime(1092941466, 'unixepoch');
select strftime('%s','now') -strftime('%s','1991-03-06 13:34:56');
SELECT TIME ('12:00','utc');

SELECT * FROM TEST where age is not null;
SELECT * FROM TEST where name like 'ki%';
SELECT * FROM TEST where name like 'p__l';
SELECT * FROM TEST where name like '%a%';
SELECT * FROM TEST where name like '_a%';
SELECT * FROM TEST where age in (25,27);
SELECT * FROM TEST where age not in (25,27);
SELECT * FROM TEST where age between 25 and 27;
SELECT * FROM TEST where age in (27) and salary>=65000;
SELECT * FROM TEST where age >=25 or salary>=65000;

SELECT * FROM TEST ORDER BY name ASC;
SELECT * FROM TEST ORDER BY name,age ASC;
SELECT * FROM TEST ORDER BY age DESC;

INSERT INTO TEST VALUES (7, 'Dylan', 26, 'France', 7800.00);
INSERT INTO TEST VALUES (8, 'Luke', 27, 'Newyork', 65000.00);
INSERT INTO TEST VALUES (9, 'Justin', 32, 'NewMexico', 50800.00);

SELECT NAME, SUM(SALARY) AS TOTAL FROM TEST GROUP BY NAME;
SELECT NAME, SUM(SALARY) FROM TEST GROUP BY NAME ORDER BY NAME;
SELECT COUNT(*),COUNT(AGE)FROM TEST WHERE AGE>24 ;

SELECT NAME, AGE, 'YES' AS yesorno FROM TEST;
SELECT C.ID,C.NAME,C.AGE,D.DEPT FROM TEST AS C, DEPARTMENT AS D WHERE C.ID=D.EMP_ID;
SELECT C.ID AS TEST_ID, C.NAME AS COMPANY_NAME, C.AGE, D.DEPT FROM COMPANY AS C,DEPARTMENT AS D WHERE C.ID=D.EMP_ID;