
-- 권한이 'ROLE_STUDENT’을 가진 목록 : AUTHORITY_MEMBER

-- select*from AUTHORITY_MEMBER where AUTHORITY_ID  like 'ROLE_STUDENT';



-- '강의/강연 신' 조직 구조 확인 : ORGANIZATION

-- SELECT*FROM ORGANIZATION;

-- SELECT  ORGANIZATION.NAME, 
--         PARENT_ORGANIZATION_SEQ, 
--         ORGANIZATION.TYPE,
--         ORGANIZATION_SEQ

-- FROM ORGANIZATION WHERE ORGANIZATION.NAME LIKE '강의/강연 신' 
-- and PARENT_ORGANIZATION_SEQ is null


-- 이름이 'yojulab admin'인 회원 소속, 기관, 권한 종류 확인 :
-- SELECT*FROM ORGANIZATION_MEMBER;
-- SELECT*FROM AUTHORITY_MEMBER;
-- SELECT*FROM MEMBER;


-- SELECT MEMBER.MEMBER_SEQ, MEMBER.NAME, AUTHORITY_ID, ORGANIZATION_MEMBER.TYPE
-- FROM MEMBER 

-- INNER JOIN AUTHORITY_MEMBER
-- ON MEMBER.MEMBER_SEQ=AUTHORITY_MEMBER.MEMBER_SEQ and MEMBER.NAME LIKE 'yojulab Admin'
-- INNER JOIN ORGANIZATION_MEMBER
-- ON MEMBER.MEMBER_SEQ=ORGANIZATION_MEMBER.MEMBER_SEQ and MEMBER.NAME LIKE 'yojulab Admin';
